### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by trueChazza**
v2.0.0

Breaking change - Added SQLite, removed PostgreSQL

### CODE REVIEW

**Comment by trueChazza** [comment]
v2.0.0

**Comment by aleksasiriski** [comment]
Bring back PostgreSQL, it's more robust and you can scale midarr in kubernetes

**Comment by stavros-k** [comment]
> Bring back PostgreSQL, it's more robust and you can scale midarr in kubernetes

Exactly.. SQLite will corrupt within a week on network storage -.-

**Comment by Ornias1993** [comment]
How is this even named an "improvement"?

**Comment by aleksasiriski** [comment]
SQLite has it's usecases, it's much lower latency for example, but still Postgres is much more reliable and has proper support for scaling and sharding.

**Comment by aleksasiriski** [comment]
It's also relatively easy to support both, they have the same SQL syntax except for 2 things:
1. In place of variables SQLite expects `?` whereas Postgres uses `%s`
2. Primary key is `integer` in SQLite whereas Postgres uses `serial`
Both of those cases can be easily adjusted using local variables, like I did [here](https://github.com/joshuaboniface/rffmpeg/pull/51)

**Comment by Ornias1993** [comment]
> SQLite has it's usecases, it's much lower latency for example, but still Postgres is much more reliable and has proper support for scaling and sharding.

Definately true, more in the sense of "when is removing a feature" an improvement if the new features isn't 100% superior".

**Comment by Ornias1993** [comment]
>   like I did [here](https://github.com/joshuaboniface/rffmpeg/pull/51)

Going to keep that project in mind btw ;-)

**Comment by aleksasiriski** [comment]
> > like I did [here](https://github.com/joshuaboniface/rffmpeg/pull/51)
> 
> Going to keep that project in mind btw ;-)

If you like that, check [this](https://github.com/aleksasiriski/jellyfin-rffmpeg) out.

**Pull request merged**
