### PR TITLE
feat: Reduce container image size

### PR DESCRIPTION
**Pull request by onedr0p**
Fixes https://github.com/midarrlabs/midarr-server/issues/317

### CODE REVIEW

**Comment by onedr0p** [comment]
Should be good to review, but I don't see any tests kicking off.

**Comment by trueChazza** [comment]
Yeah I'm seeing why the build hasn't started. One moment...

**Comment by trueChazza** [comment]
Build running 😄

**Review by trueChazza — APPROVED** [review]
Awesome thanks again!

**Pull request merged**
